{% set name = "restrictedpython" %}
{% set version = "8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3af2312bc67e5fced887fb85b006c89861da72488128b155beea81eb6a0a9b24

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.13
  run:
    - python >=3.7,<3.13

test:
  imports:
    - RestrictedPython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/RestrictedPython
  summary: RestrictedPython is a defined subset of the Python language which allows to provide a program input into a trusted environment.
  dev_url: https://github.com/zopefoundation/RestrictedPython
  license: ZPL-2.1
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - BubblyOrca
    - mxr-conda
