{% set name = "restrictedpython" %}
{% set version = "7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/RestrictedPython-{{ version }}.tar.gz
  sha256: 875aeb51c139d78e34cef8605dc65309b449168060dd08551a1fe9edb47cb9a5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python <3.12
  run:
    - python <3.12

test:
  imports:
    - RestrictedPython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/RestrictedPython
  summary: RestrictedPython is a defined subset of the Python language which allows to provide a program input into a trusted environment.
  dev_url: https://github.com/zopefoundation/RestrictedPython
  license: ZPL-2.1
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - BubblyOrca
    - mxr-conda
    - hadim
