{% set name = "restrictedpython" %}
{% set version = "7.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/RestrictedPython-{{ version }}.tar.gz
  sha256: 8888304c7858fdcfd86c50b58561797375ba40319d2b6ffb5d24b08b6a2dcd61

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.13
  run:
    - python >=3.7,<3.13

test:
  imports:
    - RestrictedPython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/RestrictedPython
  summary: RestrictedPython is a defined subset of the Python language which allows to provide a program input into a trusted environment.
  dev_url: https://github.com/zopefoundation/RestrictedPython
  license: ZPL-2.1
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - BubblyOrca
    - mxr-conda
