schema_version: 1

context:
  version: "8.5"

package:
  name: restrictedpython
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/restrictedpython/restrictedpython-${{ version }}.tar.gz
  sha256: 4ed1269dbe3caa88db650d1af325198a952aeb1451eca05df0cfa65db4466215

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=78.1.1,<82
    - wheel
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - RestrictedPython
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: RestrictedPython is a defined subset of the Python language which allows to provide a program input into a trusted environment.
  license: ZPL-2.1 AND BSD-3-Clause
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt
  homepage: https://github.com/zopefoundation/RestrictedPython
  repository: https://github.com/zopefoundation/RestrictedPython
  documentation: https://restrictedpython.readthedocs.io/

extra:
  recipe-maintainers:
    - BubblyOrca
    - mxr-conda
    - mgorny
